version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: fractal_math_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_actual_password
      POSTGRES_DB: fractal_math
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 